### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by pradeepnair74** [sandboxforgithubtraining/real-deal#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by pradeep-nair74** [comment]
Hello There

**Comment by rs2887** [comment]
Hi

**Comment by msvikas** [comment]
Hello There

**Comment by aravindhghosh** [comment]
Hi

**Comment by Thangamari-G** [comment]
Hello

**Comment by Kalidbaby** [comment]
Hello

**Comment by cgoenka1** [comment]
comment ;-)

**Comment by Mark84ster** [comment]
Hi

**Comment by raj1504** [comment]
Hello

**Comment by ukarmakar** [comment]
Test

**Comment by nihar-panda-personal** [comment]
From BY-Git-Training

**Comment by suresha-snowflake** [comment]
Hello - Test

**Comment by mogerkrishna** [comment]
done

**Comment by Satyadutta** [comment]
Hi
